version: '3.4'

services:
  casestudydb:
    image: mcr.microsoft.com/mssql/server

  casestudy.presentation:
    image: ${DOCKER_REGISTRY-}casestudypresentation
    build:
      context: .
      dockerfile: Task.Presentation/Dockerfile
